// NEW 상품 데이터

const womenData = {
    item0: {
        name: "와이드 라운드 버클 단화 2.0 HPWWVD217M",
        img: "item_1",
        oprice:"39900",
        dprice: "37900",
        sale:"",
    },
    item1: {
        name: "바게트 숄더백 HPABGD202M",
        img: "item_2",
        oprice:"",
        dprice: "39900",
        sale:"",
    },
    item2:{
        name: "네프사 캔디컬러 미들 삭스 HPAO5DA18Q",
        img: "item_3",
        oprice:"",
        dprice: "5900",
        sale:"",
    },
    item3:{
        name: "[경량EVA] 더블 스트랩 리커버리 슬리퍼 HPCV4D244M",
        img: "item_4",
        oprice:"25900",
        dprice: "24900",
        sale:"",
    },
    item4:{
        name: "[경량EVA] 아웃도어 투 벨크로 샌들 HPCV4D242M",
        img: "item_5",
        oprice:"39900",
        dprice: "37900",
        sale:"",
    },
    item5:{
        name: "[도영도영이 PICK] 캔버스 쇼퍼백 HPABGD225M",
        img: "item_6",
        oprice:"39900",
        dprice: "37900",
        sale:"",
    },
    item6:{
        name: "캔버스 핸드폰백 HPABGD226M",
        img: "item_7",
        oprice:"25900",
        dprice: "24900",
        sale:"",
    },
    item7:{
        name: "캔버스 버킷백 HPABGD224M",
        img: "item_8",
        oprice:"39900",
        dprice: "37900",
        sale:"",
    },
    item8:{
        name: "[경량EVA] 논슬립 베이직 리커버리 쪼리 HPCV5D251M",
        img: "item_9",
        oprice:"19900",
        dprice: "18900",
        sale:"",
    },
    item9:{
        name: "링클 버킷햇 HPACSD304M",
        img: "item_10",
        oprice:"29900",
        dprice: "27900",
        sale:"",
    },
    item10: {
        name: "[도영도영이 PICK] 코튼 블렌드 케이블 버킷햇 HPACSD301M",
        img: "item_11",
        oprice:"29900",
        dprice: "27900",
        sale:"",
    },
    item11:{
        name: "라운드 투스트랩 밴딩 슬라이드 1.0 HPWWID231D",
        img: "item_12",
        oprice:"19900",
        dprice: "18900",
        sale:"",
    },
    item12: {
        name: "[경량EVA] 논슬립 페인팅 리커버리 쪼리 HPCV5D382M",
        img: "item_13",
        oprice:"29900",
        dprice: "27900",
        sale:"",
    },
    item13: {
        name: "[경량EVA] 컬러풀 리커버리 클로그 HPCV4D386M",
        img: "item_14",
        oprice:"35900",
        dprice: "33900",
        sale:"",
    },
    item14: {
        name: "[테니스클럽] 그래픽 골지 미들 삭스 HPAO5DA17Q",
        img: "item_15",
        oprice:"",
        dprice: "5900",
        sale:"",
    },
    item15: {
        name: "에스파듀 패턴 샌들 2.0 HPWWND321Q",
        img: "item_16",
        oprice:"39900",
        dprice: "37900",
        sale:"",
    },
    item16: {
        name: "에스파듀 패턴 슬라이드 2.0 HPWWID321Q",
        img: "item_17",
        oprice:"39900",
        dprice: "37900",
        sale:"",
    },
    item17: {
        name: "네이비 3M 스트링 백팩 HPADZC401N",
        img: "item_18",
        oprice:"59900",
        dprice: "53900",
        sale:"",
    },
    item18: {
        name: "밴딩 첼시 레인부츠 HPCV7D383W",
        img: "item_19",
        oprice:"35900",
        dprice: "33900",
        sale:"",
    },
    item19: {
        name: "캐스퍼 미니 토트백 TPBT79W32",
        img: "item_20",
        oprice:"25900",
        dprice: "19900",
        sale:"",
    },
}

const menData = {
    item0: {
        name: "아이스락 하이퍼그립 첼시부츠 (HPMV9C404M RE) HPMV9DA04M",
        img: "item_1",
        oprice:"",
        dprice: "159000",
        sale:"",
    },
    item1: {
        name: "[슈탠다드] 남성 컬러 골지크루 삭스 HPAO5DA19M",
        img: "item_2",
        oprice:"",
        dprice: "3900",
        sale:"",
    },
    item2: {
        name: "마하그리드 스트링 백팩 HPADZDA05M",
        img: "item_3",
        oprice:"59900",
        dprice: "56900",
        sale:"",
    },
    item3: {
        name: "[드로우핏 X 슈펜] 베이직 레더 더비 HPMR7CA51M",
        img: "item_4",
        oprice:"",
        dprice: "129000",
        sale:"",
    },
    item4: {
        name: "🌟TOP 5 [오솔라이트] 유니 레더 독일군 HPMR6DA03M",
        img: "item_5",
        oprice:"",
        dprice: "59900",
        sale:"",
    },
    item5: {
        name: "이지라이트 컴포트 어텁 레이스 펀칭더비 BYSL79A12",
        img: "item_6",
        oprice:"39900",
        dprice: "23630",
        sale:"",
    },
    item6: {
        name: "네이비 3M 스트링 백팩 HPADZC401N",
        img: "item_7",
        oprice:"59900",
        dprice: "53900",
        sale:"",
    },
    item7: { 
        name: "[핏더사이즈X슈펜] Seku-shi(세쿠시) 첼시 부읏츠 (다크 브라운 / 아이보리)",
        img: "item_8",
        oprice:"",
        dprice: "159000",
        sale:"",
    },
    item8: {
        name: "22 베이직 키높이 스니커즈_HPMR6CA04M",
        img: "item_9",
        oprice:"59900",
        dprice: "53900",
        sale:"",
    },
    item9: {
        name: "남성 레더 드라이빙로퍼_스웨이드 페니(HPMR9C471M RE) HPMR9DA11M",
        img: "item_10",
        oprice:"79900",
        dprice: "75900",
        sale:"",
    },
    item10: {
        name: "드로우핏 X 슈펜 로퍼 HPMR7DA56M",
        img: "item_11",
        oprice:"79900",
        dprice: "75900",
        sale:"",
    },
    item11: {
        name: "드로우핏 X 슈펜 더비 HPMR7DA55M",
        img: "item_12",
        oprice:"79900",
        dprice: "75900",
        sale:"",
    },
    item12: {
        name: "[초경량] 논슬립 슬림 슈레이스 워킹화 HPCR5DA23M",
        img: "item_13",
        oprice:"39900",
        dprice: "37900",
        sale:"",
    },
    item13: {
        name: "[초경량] 논슬립 베이직 슬립온 워킹화 HPCR5DA31Q",
        img: "item_14",
        oprice:"39900",
        dprice: "37900",
        sale:"",
    },
    item14: {
        name: "유니 모던 캐주얼 키높이 더비 HPMR7DA02M",
        img: "item_15",
        oprice:"59900",
        dprice: "56900",
        sale:"",
    },
    item15: {
        name: "유니 모던 캐주얼 로퍼 HPMR7DA04Q",
        img: "item_16",
        oprice:"59900",
        dprice: "56900",
        sale:"",
    },
    item16: {
        name: "유니모던 캐주얼 더비 HPMR7DA01Q",
        img: "item_17",
        oprice:"59900",
        dprice: "56900",
        sale:"",
    },
    item17: {
        name: "[NAVY] 2포켓 빅 반달 메신저백 HPABCD206M",
        img: "item_18",
        oprice:"39900",
        dprice: "37900",
        sale:"",
    },
    item18: {
        name: "[NAVY] 가벼운 반달포켓 크로스백 HPABCD207M",
        img: "item_19",
        oprice:"29900",
        dprice: "27900",
        sale:"",
    },
    item19: {
        name: "남성 베이직 쿠션 샌들 HPMV4D210M",
        img: "item_20",
        oprice:"59900",
        dprice: "56900",
        sale:"",
    },
}

const kidsData = {
    item0: {
        name: "[디즈니] 앨리스 라이팅 샌들 HPKWND21DG",
        img: "item_1",
        oprice:"39900",
        dprice: "35900",
        sale:"",
    },
    item1: {
        name: "키즈 샤이닝 레인부츠 HPKV6DA01Q",
        img: "item_2",
        oprice:"29900",
        dprice: "26910",
        sale:"",
    },
    item2: {
        name: "키즈 크레용 버클 쿠션 샌들 HPKWND212G",
        img: "item_3",
        oprice:"29900",
        dprice: "26910",
        sale:"",
    },
    item3: {
        name: "[디즈니] 앨리스 하트 크로스백 HPKBXDA1DG",
        img: "item_4",
        oprice:"35900",
        dprice: "32310",
        sale:"",
    },
    item4: {
        name: "키즈 플랫폼 베이직 샌들 HPKWND211G",
        img: "item_5",
        oprice:"29900",
        dprice: "26910",
        sale:"",
    },
    item5: {
        name: "키즈 썸머 스트랩 쿠션 샌들 HPKV4D202U",
        img: "item_6",
        oprice:"29900",
        dprice: "26910",
        sale:"",
    },
    item6: {
        name: "[디즈니] 앨리스 헤어핀 세트 HPKZZDA1DG",
        img: "item_7",
        oprice:"19900",
        dprice: "17910",
        sale:"",
    },
    item7: { 
        name: "[레인보우] 리본 탈부착 글리터 플랫 HPKWVD224G",
        img: "item_8",
        oprice:"29900",
        dprice: "24220",
        sale:"",
    },
    item8: {
        name: "키즈 경량 리커버리 샌들 HPKV0D202U",
        img: "item_9",
        oprice:"29900",
        dprice: "25900",
        sale:"",
    },
    item9: {
        name: "키즈 버클 EVA 샌들 HPKV4D201U",
        img: "item_10",
        oprice:"29900",
        dprice: "25900",
        sale:"",
    },
    item10: {
        name: "키즈 스마일 스니커즈 4족 세트 HPKL4DA07U",
        img: "item_11",
        oprice:"9900",
        dprice: "9400",
        sale:"",
    },
    item11: {
        name: "키즈 치즈 스니커즈 4족 세트 HPKL4DA08U",
        img: "item_12",
        oprice:"9900",
        dprice: "9400",
        sale:"",
    },
    item12: {
        name: "여아 유니콘 스니커즈 4족 세트 HPKL4DA09G",
        img: "item_13",
        oprice:"9900",
        dprice: "9400",
        sale:"",
    },
    item13: {
        name: "키즈 스트라이프 덧신 5족 세트 HPKL4DA06U",
        img: "item_14",
        oprice:"9900",
        dprice: "9400",
        sale:"",
    },
    item14: {
        name: "키즈 스트라이프 스니커즈 5족 세트 HPKL4DA05U",
        img: "item_15",
        oprice:"9900",
        dprice: "9400",
        sale:"",
    },
    item15: {
        name: "키즈 컬러블록 스니커즈 4족 세트 HPKL4DA04U",
        img: "item_16",
        oprice:"9900",
        dprice: "9400",
        sale:"",
    },
    item16: {
        name: "[레인보우] 레이스 토오픈 라이팅 구두 HPKWVD225G",
        img: "item_17",
        oprice:"39900",
        dprice: "35910",
        sale:"",
    },
    item17: {
        name: "키즈 메리제인 쿠션플랫 HPKWFD205G",
        img: "item_18",
        oprice:"29900",
        dprice: "26910",
        sale:"",
    },
    item18: {
        name: "키즈 메쉬 버킷햇 HPKACD201U",
        img: "item_19",
        oprice:"29900",
        dprice: "26910",
        sale:"",
    },
    item19: {
        name: "키즈 경량 EVA 샌들 HPKV0D204U",
        img: "item_20",
        oprice:"25900",
        dprice: "23310",
        sale:"",
    },
}

// 타겟 서브페이지 상품데이터 
const tgData = {
    "women": {
        "shoes": {
            flat:[
                {
                    name:"🌟TOP 5 [가드너] 스윗버튼 메리제인 플랫 1.0 HPWWFD202S",
                    img: "item_1",
                    oprice: "29900",
                    dprice: "28900",
                    sale: "",
                    review: "170"
                },
                {
                    name:"V컷 스퀘어 쿠션 플랫 1.0 HPWWFC401S",
                    img: "item_2",
                    oprice: "19900",
                    dprice: "14880",
                    sale: "",
                    review: "63"
                },
                {
                    name:"쿠션 플랫 1.0 HPWWFCA01S",
                    img: "item_3",
                    oprice: "19900",
                    dprice: "14880",
                    sale: "",
                    review: "127"
                },
                {
                    name:"[가드너] 스퀘어 리본 플랫슈즈 HPWWFDA01S",
                    img: "item_4",
                    oprice: "25900",
                    dprice: "24900",
                    sale: "",
                    review: "3"
                },
                {
                    name:"와이드 라운드 버클 단화 2.0 HPWWVD217M",
                    img: "item_5",
                    oprice: "39900",
                    dprice: "37900",
                    sale: "",
                    review: "29"
                },
                {
                    name:"베이직 메리제인 플랫 1.0 HPWWFC402S",
                    img: "item_6",
                    oprice: "19900",
                    dprice: "14880",
                    sale: "",
                    review: "129"
                },
                {
                    name:"스퀘어 힐밴딩 플랫 1.0 MIST78S02",
                    img: "item_7",
                    oprice: "19900",
                    dprice: "14880",
                    sale: "",
                    review: "100"
                },
                {
                    name:"라운드토 니트 플랫 1.0 MIST79S04",
                    img: "item_8",
                    oprice: "15900",
                    dprice: "12380",
                    sale: "",
                    review: "115"
                },
                {
                    name:"발레리나 메리제인 플랫 HPWWFDA90Q",
                    img: "item_9",
                    oprice: "39900",
                    dprice: "37900",
                    sale: "",
                    review: "6"
                },
                {
                    name:"Q 메리제인 웰트 단화 1.5 MISW79S42",
                    img: "item_10",
                    oprice: "29900",
                    dprice: "18630",
                    sale: "",
                    review: "19"
                },
                {
                    name:"에어핏쿠션 메리제인 단화 3.0 HPWWVC407S",
                    img: "item_11",
                    oprice: "39900",
                    dprice: "23630",
                    sale: "",
                    review: "23"
                },
                {
                    name:"오블리크 V컷 플랫 HPWWFD201S",
                    img: "item_12",
                    oprice: "29900",
                    dprice: "27900",
                    sale: "",
                    review: "13"
                },
                {
                    name:"쿠션 플랫 1.0 MIST79A01",
                    img: "item_13",
                    oprice: "15900",
                    dprice: "12380",
                    sale: "",
                    review: "103"
                },
                {
                    name:"캔버스 슬립온 에스파듀 AFHL78S01",
                    img: "item_14",
                    oprice: "19900",
                    dprice: "14880",
                    sale: "",
                    review: "6"
                },
                {
                    name:"스퀘어 밴딩 바부슈 플랫 1.0 HPWWFB403M",
                    img: "item_15",
                    oprice: "19900",
                    dprice: "14880",
                    sale: "",
                    review: "43"
                },
                {
                    name:"글로시 메리제인 플랫 1.5 HPWWFC403S",
                    img: "item_16",
                    oprice: "29900",
                    dprice: "18630",
                    sale: "",
                    review: "63"
                },
                {
                   name:"[가드너] 스퀘어 메리제인 플랫슈즈 HPWWFDA03S",
                   img: "item_17",
                   oprice: "29900",
                   dprice: "27900",
                   sale: "",
                   review: "7" 
                },
                {
                    name:"슈블리 메리제인 플랫 MIST78S52",
                    img: "item_18",
                    oprice: "39900",
                    dprice: "23630",
                    sale: "",
                    review: "25"
                },
                {
                    name:"포인트 민자 단화 1.0 MIST79W06",
                    img: "item_19",
                    oprice: "29900",
                    dprice: "18630",
                    sale: "",
                    review: "8"
                },
                {
                    name:"쭈언니픽 메리제인 컬러 니트 플랫 1.0 MIST78S04",
                    img: "item_20",
                    oprice: "19900",
                    dprice: "17900",
                    sale: "",
                    review: "14"
                },
                {
                   name:"메리제인 웰트 플랫 1.0 MIST79W04",
                   img: "item_17",
                   oprice: "29900",
                   dprice: "22900",
                   sale: "",
                   review: "13" 
                },
                {
                    name:"메리제인 발레슈 단화 1.0 HPWWVD204M",
                    img: "item_18",
                    oprice: "39900",
                    dprice: "37900",
                    sale: "",
                    review: "17"
                },
                {
                    name:"DRP드롭_메리제인플랫 MIST78S09",
                    img: "item_19",
                    oprice: "29900",
                    dprice: "26900",
                    sale: "",
                    review: "15"
                },
                {
                    name:"와이드 라운드 메리제인 단화 2.0 HPWWVD218M",
                    img: "item_20",
                    oprice: "39900",
                    dprice: "37900",
                    sale: "",
                    review: "2"
                },
            ],
            
            sandal: [
                {
                    name:"패턴 커버 플랫 샌들 1.5 MIDW78S14",
                    img:"item_1",
                    oprice:"19900",
                    dprice:"14880",
                    sale:"",
                    review:"5",
                },
                {
                    name:"플랫폼 피셔맨 샌들 3.5 HPWWND204M",
                    img:"item_2",
                    oprice:"39900",
                    dprice:"35910",
                    sale:"",
                    review:"33",
                },
                {
                    name:"스퀘어 스트랩 샌들 2.5 MIDW78S01",
                    img:"item_3",
                    oprice:"19900",
                    dprice:"14880",
                    sale:"",
                    review:"32",
                },
                {
                    name:"와이드 플랫 피셔맨 샌들 1.0 HPWWND203M",
                    img:"item_4",
                    oprice:"39900",
                    dprice:"35910",
                    sale:"",
                    review:"26",
                },
                {
                    name:"쿠션 투 스트랩 샌들 AFDM78S02",
                    img:"item_5",
                    oprice:"29900",
                    dprice:"18630",
                    sale:"",
                    review:"25",
                },
                {
                    name:"[도영도영이 PICK] 라운드 커버 단화샌들 1.0 HPWWND201S",
                    img:"item_6",
                    oprice:"29900",
                    dprice:"26910",
                    sale:"",
                    review:"89",
                },
                {
                    name:"[경량EVA] 아웃도어 투 벨크로 샌들 HPCV4D242M",
                    img:"item_7",
                    oprice:"39900",
                    dprice:"37900",
                    sale:"",
                    review:"1",
                },
                {
                    name:"쿠션 플랫폼 스트랩 샌들 4.0 MIDW78S07",
                    img:"item_8",
                    oprice:"29900",
                    dprice:"18630",
                    sale:"",
                    review:"16",
                },
                {
                    name:"스퀘어 스트랩 샌들 5.0 MIDW78S02",
                    img:"item_9",
                    oprice:"29900",
                    dprice:"18630",
                    sale:"",
                    review:"19",
                },
                {
                    name:"X 스트랩 쿠션 웨지 샌들 6.5 MIDW78S19",
                    img:"item_10",
                    oprice:"29900",
                    dprice:"18630",
                    sale:"",
                    review:"19",
                },
                {
                    name:"리커버리 소프트 젤리샌들 HPCV1D381Q",
                    img:"item_11",
                    oprice:"19900",
                    dprice:"17910",
                    sale:"",
                    review:"",
                },
                {
                    name:"에어핏 쿠션 베이직 덮개 뮬 4.0 MIDL78S04",
                    img:"item_12",
                    oprice:"29900",
                    dprice:"18630",
                    sale:"",
                    review:"10",
                },
                {
                    name:"오블리크 스트랩 샌들 2.0 MIDW78S12",
                    img:"item_13",
                    oprice:"19900",
                    dprice:"14880",
                    sale:"",
                    review:"5",
                },
                {
                    name:"베이직 웨지 샌들 5.0 MIDW78S21",
                    img:"item_14",
                    oprice:"29900",
                    dprice:"18630",
                    sale:"",
                    review:"14",
                },
                {
                    name:"스팽클 투밴드 웻지 슬리퍼 AFDL79S14",
                    img:"item_15",
                    oprice:"19900",
                    dprice:"14880",
                    sale:"",
                    review:"6",
                },
                {
                    name:"투웨이 웨지 샌들 5.0 MIDW78S22",
                    img:"item_16",
                    oprice:"29900",
                    dprice:"18630",
                    sale:"",
                    review:"1",
                },
                {
                    name:"베이직 스트랩 샌들 5.0 MIDW79S01",
                    img:"item_17",
                    oprice:"29900",
                    dprice:"22900",
                    sale:"",
                    review:"23",
                },
                {
                    name:"메쉬 스트랩 쿠션 웨지 샌들 6.5 MIDW78S20",
                    img:"item_18",
                    oprice:"29900",
                    dprice:"18630",
                    sale:"",
                    review:"8",
                },
                {
                    name:"피셔맨 힐 샌들 HPWWND252D",
                    img:"item_19",
                    oprice:"49900",
                    dprice:"44910",
                    sale:"",
                    review:"",
                },
                {
                    name:"T스트랩 플랫폼 샌들 3.0 MIDW78S06",
                    img:"item_20",
                    oprice:"29900",
                    dprice:"26900",
                    sale:"",
                    review:"",
                },
            ],
        },
        "bags": {
            backpack:[
                {
                    name:"푸우 레이 백팩 TPBK79S52",
                    img:"item_1",
                    oprice:"",
                    dprice:"29900",
                    sale:"",
                    review:"23",
                },
                {
                    name:"[테디아일랜드] 베이직 백팩 HPADZDA01C",
                    img:"item_2",
                    oprice:"29900",
                    dprice:"27900",
                    sale:"",
                    review:"1",
                },
                {
                    name:"전황일콜라보 매쉬백팩 TPBK79W72",
                    img:"item_3",
                    oprice:"69900",
                    dprice:"55900",
                    sale:"",
                    review:"10",
                },
                {
                    name:"네이비 3M 스트링 백팩 HPADZC401N",
                    img:"item_4",
                    oprice:"59900",
                    dprice:"53900",
                    sale:"",
                    review:"",
                },
                {
                    name:"[테디아일랜드] 멀티 매쉬 백팩 HPADZDA02C",
                    img:"item_5",
                    oprice:"59900",
                    dprice:"56900",
                    sale:"",
                    review:"1",
                },
                {
                    name:"나일론 미니 백팩 BLBK78S15",
                    img:"item_6",
                    oprice:"29900",
                    dprice:"26900",
                    sale:"",
                    review:"3",
                },
                {
                    name:"네이비 X 베이직 백팩 HPADZC433M",
                    img:"item_7",
                    oprice:"29900",
                    dprice:"26900",
                    sale:"",
                    review:"1",
                },
                {
                    name:"MADE BY 쭈언니 백팩 BLBP78S25",
                    img:"item_8",
                    oprice:"99000",
                    dprice:"88900",
                    sale:"",
                    review:"5",
                },
                {
                    name:"마하 그리드 로고 베이직 백팩 TPBK78S71",
                    img:"item_9",
                    oprice:"29900",
                    dprice:"26900",
                    sale:"",
                    review:"16",
                },
                {
                    name:"브루클린 스트링 백팩 TPBK78S05",
                    img:"item_10",
                    oprice:"39900",
                    dprice:"35900",
                    sale:"",
                    review:"3",
                },
            ],
            minibag:[
                {
                    name:"크로셰 핸드폰 백 BLBK78S11",
                    img:"",
                    oprice:"15900",
                    dprice:"12900",
                    sale:"",
                    review:"3",
                },
                {
                    name:"나일론 셔링 미니백 HPABGD221M",
                    img:"",
                    oprice:"25900",
                    dprice:"24900",
                    sale:"",
                    review:"",
                },
                {
                    name:"데일리 나일론 미니 숄더백 HPABGC407M",
                    img:"",
                    oprice:"29900",
                    dprice:"26900",
                    sale:"",
                    review:"1",
                },
                {
                    name:"캐스퍼 백인백 TPAC79W31",
                    img:"",
                    oprice:"",
                    dprice:"15900",
                    sale:"",
                    review:"16",
                },
                {
                    name:"네트 핸드폰 백 BLBK78S08",
                    img:"",
                    oprice:"19900",
                    dprice:"17900",
                    sale:"",
                    review:"",
                },
                {
                    name:"캐스퍼 미니 토트백 TPBT79W32",
                    img:"",
                    oprice:"25900",
                    dprice:"19900",
                    sale:"",
                    review:"16",
                },
                {
                    name:"가벼운 스트링 핸드폰백 HPABXC432M",
                    img:"",
                    oprice:"19900",
                    dprice:"17900",
                    sale:"",
                    review:"1",
                },
                {
                    name:"패턴 미니백 TPBT78S06",
                    img:"",
                    oprice:"",
                    dprice:"15900",
                    sale:"",
                    review:"4",
                },
                {
                    name:"뉴반달 S BLBC79W01",
                    img:"",
                    oprice:"35900",
                    dprice:"27900",
                    sale:"",
                    review:"4",
                },
                {
                    name:"슈펜 베이직 핸드폰 가방 TPBC79W01",
                    img:"",
                    oprice:"",
                    dprice:"15900",
                    sale:"",
                    review:"4",
                },
                {
                    name:"[NAVY] 베이직 와펜 핸드폰 가방 HPABCD205M",
                    img:"",
                    oprice:"19900",
                    dprice:"18900",
                    sale:"",
                    review:"",
                },
                {
                    name:"마하 그리드 베이직 사코슈백 TPBC78S75",
                    img:"",
                    oprice:"25900",
                    dprice:"22900",
                    sale:"",
                    review:"8",
                },
                {
                    name:"미니 볼링백 BLBC79W13",
                    img:"",
                    oprice:"39900",
                    dprice:"30900",
                    sale:"",
                    review:"4",
                },
                {
                    name:"CHEWY MINIBAG BLBC78S20",
                    img:"",
                    oprice:"",
                    dprice:"15900",
                    sale:"",
                    review:"",
                },
                {
                    name:"캔버스 아코디언 BLBC78S07",
                    img:"",
                    oprice:"39900",
                    dprice:"35900",
                    sale:"",
                    review:"3",
                },
                {
                    name:"에코 미니 토트백 HPABDC456M",
                    img:"",
                    oprice:"",
                    dprice:"15900",
                    sale:"",
                    review:"",
                },
                {
                    name:"바게트 미니백 HPABXC405M",
                    img:"",
                    oprice:"39900",
                    dprice:"35900",
                    sale:"",
                    review:"2",
                },
                {
                    name:"클래식 미니백 HPABXC401O",
                    img:"",
                    oprice:"49900",
                    dprice:"44900",
                    sale:"",
                    review:"1",
                },
                {
                    name:"슬림 미니백 HPABXC412M",
                    img:"",
                    oprice:"29900",
                    dprice:"26900",
                    sale:"",
                    review:"",
                },
                {
                    name:"미니스퀘어 HPABXC401M",
                    img:"",
                    oprice:"29900",
                    dprice:"26900",
                    sale:"",
                    review:"1",
                },
            ],
        },
        "ac": {
            socks:[
                {
                    name:"슈탠다드 남녀 데일리 페이크 삭스 10팩 LGKA79A01",
                    img:"",
                    oprice:"",
                    dprice:"17900",
                    sale:"",
                    review:"65",
                },
                {
                    name:"슈탠다드 양말_남녀 쇼트 10팩 LGKA79A21",
                    img:"",
                    oprice:"",
                    dprice:"17900",
                    sale:"",
                    review:"5",
                },
                {
                    name:"슈탠다드 양말_남녀 클래식 골지 7팩 LGKA20A07",
                    img:"",
                    oprice:"",
                    dprice:"12900",
                    sale:"",
                    review:"45",
                },
                {
                    name:"[슈탠다드] 여성 논슬립 풋커버 삭스 3팩 HPAO7DA13U",
                    img:"",
                    oprice:"",
                    dprice:"7900",
                    sale:"",
                    review:"",
                },
                {
                    name:"[슈탠다드] 남녀공용 5팩 페이크 삭스 (라이트웨이트) HPAO7DA11U",
                    img:"",
                    oprice:"",
                    dprice:"9900",
                    sale:"",
                    review:"",
                },
                {
                    name:"여성 골지 니삭스 HPAO2DA14Q",
                    img:"",
                    oprice:"",
                    dprice:"5900",
                    sale:"",
                    review:"2",
                },
                {
                    name:"슈탠다드 양말_여성 레귤러 무지 7팩 LGKB20A02",
                    img:"",
                    oprice:"",
                    dprice:"10000",
                    sale:"",
                    review:"7",
                },
                {
                    name:"슈탠다드 양말_여성 숏앵클 7팩 LGKB20A03",
                    img:"",
                    oprice:"",
                    dprice:"10000",
                    sale:"",
                    review:"10",
                },
                {
                    name:"여성 페이크삭스 2팩 LGKC20A01",
                    img:"",
                    oprice:"",
                    dprice:"3900",
                    sale:"",
                    review:"7",
                },
                {
                    name:"[슈탠다드] 남녀공용 쿠션 골지 크루삭스 5팩 (HPAO3CA41M RE) HPAO3DA41M",
                    img:"",
                    oprice:"",
                    dprice:"12900",
                    sale:"",
                    review:"1",
                },
                {
                    name:"슈탠다드 양말_남녀 하프삭스 7팩 LGKA79A23",
                    img:"",
                    oprice:"",
                    dprice:"17900",
                    sale:"",
                    review:"7",
                },
                {
                    name:"서머 푸우 자수양말 2 LGKW79S13",
                    img:"",
                    oprice:"",
                    dprice:"3900",
                    sale:"",
                    review:"51",
                },
                {
                    name:"[테니스클럽] 그래픽 골지 미들 삭스 HPAO5DA17Q",
                    img:"",
                    oprice:"",
                    dprice:"5900",
                    sale:"",
                    review:"2",
                },
                {
                    name:"파스텔 컬러 골지 링클 삭스 HPAO5DA22U",
                    img:"",
                    oprice:"",
                    dprice:"3900",
                    sale:"",
                    review:"2",
                },
                {
                    name:"슈탠다드 베이직 골지 크루 삭스 5팩 HPAO3CA43M",
                    img:"",
                    oprice:"",
                    dprice:"12900",
                    sale:"",
                    review:"6",
                },
                {
                    name:"블로퍼용 페이크삭스 2팩 LGKC20A06",
                    img:"",
                    oprice:"",
                    dprice:"2900",
                    sale:"",
                    review:"13",
                },
                {
                    name:"[슈탠다드] 남녀공용 3팩 페이크 삭스 (라이트웨이트) HPAO7DA12U",
                    img:"",
                    oprice:"",
                    dprice:"7900",
                    sale:"",
                    review:"",
                },
                {
                    name:"슈탠다드 스니커즈 삭스 5팩 HPAO3CA45M",
                    img:"",
                    oprice:"",
                    dprice:"12900",
                    sale:"",
                    review:"",
                },
                {
                    name:"슈탠다드 클래식 골지 크루 삭스 5팩 HPAO3CA47M",
                    img:"",
                    oprice:"",
                    dprice:"12900",
                    sale:"",
                    review:"1",
                },
                {
                    name:"여성 클래식 모노양말 LGKW20A01",
                    img:"",
                    oprice:"2900",
                    dprice:"2600",
                    sale:"",
                    review:"6",
                },
            ],
            hats:[
                {
                    name:"[도영도영이 PICK] 코튼 블렌드 케이블 버킷햇 HPACSD301M",
                    img:"",
                    oprice:"29900",
                    dprice:"27900",
                    sale:"",
                    review:"3",
                },
                {
                    name:"아일렛 베이직 버킷햇 TPCH79W02",
                    img:"",
                    oprice:"19900",
                    dprice:"15900",
                    sale:"",
                    review:"11",
                },
                {
                    name:"화섬 소프트 베이직 볼캡 TPCC79W02",
                    img:"",
                    oprice:"",
                    dprice:"10000",
                    sale:"",
                    review:"24",
                },
                {
                    name:"[캠프 네이처] 유틸리티 스포티즘 버킷햇 HPACHD221M",
                    img:"",
                    oprice:"29900",
                    dprice:"27900",
                    sale:"",
                    review:"",
                },
                {
                    name:"쿨면 내추럴 하드 버킷햇 HPACSD305M",
                    img:"",
                    oprice:"29900",
                    dprice:"26900",
                    sale:"",
                    review:"",
                },
                {
                    name:"배색 포인트 니트 버킷햇 HPACSD302M",
                    img:"",
                    oprice:"29900",
                    dprice:"27900",
                    sale:"",
                    review:"",
                },
                {
                    name:"천연 라피아 스틀랩 보터햇 TPCN78S10",
                    img:"",
                    oprice:"29900",
                    dprice:"26900",
                    sale:"",
                    review:"1",
                },
                {
                    name:"라인배색 선캡 TPCN79S01",
                    img:"",
                    oprice:"19900",
                    dprice:"15900",
                    sale:"",
                    review:"4",
                },
                {
                    name:"[캠프 네이쳐] 유틸리티 스포티즘 볼캡 HPACCD223M",
                    img:"",
                    oprice:"25900",
                    dprice:"24900",
                    sale:"",
                    review:"",
                },
                {
                    name:"페이퍼 와이드 선캡 TPCN78S13",
                    img:"",
                    oprice:"19900",
                    dprice:"17900",
                    sale:"",
                    review:"1",
                },
                {
                    name:"[테니스클럽] 테니스 그래픽 볼캡 HPACCD203M",
                    img:"",
                    oprice:"25900",
                    dprice:"24900",
                    sale:"",
                    review:"12",
                },
                {
                    name:"지사 숏 버킷햇 TPCN79S31",
                    img:"",
                    oprice:"19900",
                    dprice:"15900",
                    sale:"",
                    review:"",
                },
                {
                    name:"링클 버킷햇 HPACSD304M",
                    img:"",
                    oprice:"29900",
                    dprice:"27900",
                    sale:"",
                    review:"",
                },
                {
                    name:"네이비 N자수 볼캡 TPCC78A52",
                    img:"",
                    oprice:"19900",
                    dprice:"17900",
                    sale:"",
                    review:"3",
                },
                {
                    name:"천연 라피아 벨티드 선캡 TPCN78S12",
                    img:"",
                    oprice:"29900",
                    dprice:"26900",
                    sale:"",
                    review:"1",
                },
                {
                    name:"와이드 밴딩 선캡 TPCN79S02",
                    img:"",
                    oprice:"19900",
                    dprice:"15900",
                    sale:"",
                    review:"1",
                },
                {
                    name:"네이비 자수 버킷햇 TPCH78A51",
                    img:"",
                    oprice:"29900",
                    dprice:"26900",
                    sale:"",
                    review:"2",
                },
                {
                    name:"썸머 니트 와이어 벙거지 TPCN78S32",
                    img:"",
                    oprice:"19900",
                    dprice:"17900",
                    sale:"",
                    review:"5",
                },
                {
                    name:"크로셰 패턴 보닛햇 TPCN78S01",
                    img:"",
                    oprice:"19900",
                    dprice:"17900",
                    sale:"",
                    review:"2",
                },
                {
                    name:"네이비 볼록자수 볼캡 HPACCCA51M",
                    img:"",
                    oprice:"",
                    dprice:"19900",
                    sale:"",
                    review:"4",
                },
            ],
        },
    }, // women 데이터 //
}



export { womenData, menData , kidsData, tgData };