export default [
    {
        "idx":1,
        "gname":"나는야옷이야1",
        "category":"men",
        "gprice":"230000"
    },
    {
        "idx":2,
        "gname":"나는야옷이야2",
        "category":"men",
        "gprice":"330000"
    },
    {
        "idx":3,
        "gname":"나는야옷이야3",
        "category":"women",
        "gprice":"430000"
    },
    {
        "idx":4,
        "gname":"나는야옷이야4",
        "category":"women",
        "gprice":"530000"
    }
]